### ISSUE TITLE
Add a meta file for upcoming plugin admin UI

### ISSUE THREAD

**Issue by ArthurHoaro** [kalvn/shaarli-plugin-via#1]
See shaarli/Shaarli#388

[Example](https://github.com/ArthurHoaro/Shaarli/blob/pluginadmin/plugins/wallabag/wallabag.meta)

**Comment by kalvn** [comment]
Done! https://github.com/kalvn/shaarli-plugin-via/commit/2e55b2727a4f2773367b6958531f7a62f11a13e8
Thanks for opening this issue :)
